# Generated by Django 5.1.5 on 2026-09-25 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='academics.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='academics.schoolclass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='academics.section')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'school_class', 'section'), name='unique_class_section_as_per_year')],
            },
        ),
    ]
