# Generated by Django 5.1.5 on 2026-09-25 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_classsection'),
        ('profiles', '0002_studentguardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('TRANSFERRED', 'Transferred'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='profiles.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'class_section'), name='unique_student_class_section'), models.UniqueConstraint(fields=('class_section', 'roll_number'), name='unique_roll_number_per_class_section')],
            },
        ),
    ]
